title: Greg Portner # your name (or website title) here
logo: "/images/1553003467264.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Dynamic and results-oriented Senior Data Analyst with extensive experience leading data management initiatives and driving actionable insights for strategic decision-making. Proven expertise in developing and implementing master data management strategies, optimizing data extraction processes, and leveraging advanced analytics tools to enhance business performance. Adept at consolidating disparate data sources, designing ETL pipelines, and creating dynamic dashboards to provide a comprehensive view of donor interactions and financial operations. Skilled in SQL scripting, Python programming, and data visualization using tools like Power BI and Qlik Sense. Strong leadership and project management abilities demonstrated in successful data restructuring projects and significant process improvements. Possess a Master of Science in Business Analysis (MSBA) with a focus on data analytics and a solid foundation in quantitative analysis and finance. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/gregory-portner-professional/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
